name: Build Rust Windows EXE

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Скачиваем репозиторий
        uses: actions/checkout@v4

      - name: Устанавливаем Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Сборка EXE файла (Release)
        run: cargo build --release

      - name: Загрузка готового EXE в Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ChecksumComparator-Windows
          path: target/release/checksum-checker.exe
